#!/usr/bin/env python3
"""
BA Agent - Business Analyst
Analyzes requirements, creates Confluence documentation, and generates Jira user stories
"""

import os
import sys
import json
import requests
from datetime import datetime

# Add parent directory to path for imports
sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))

from utils import JiraHelper, ConfluenceHelper, SlackHelper, ClaudeHelper, PromptTemplates


def get_github_issue(issue_number: str):
    """Fetch GitHub issue details"""
    
    repo = os.environ['GITHUB_REPOSITORY']
    token = os.environ['GITHUB_TOKEN']
    
    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json"
    }
    
    response = requests.get(
        f"https://api.github.com/repos/{repo}/issues/{issue_number}",
        headers=headers,
        timeout=30
    )
    
    if response.status_code == 200:
        return response.json()
    else:
        raise Exception(f"Failed to fetch GitHub issue: {response.status_code}")


def post_github_comment(issue_number: str, comment: str):
    """Post a comment to GitHub issue"""
    
    repo = os.environ['GITHUB_REPOSITORY']
    token = os.environ['GITHUB_TOKEN']
    
    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json"
    }
    
    requests.post(
        f"https://api.github.com/repos/{repo}/issues/{issue_number}/comments",
        headers=headers,
        json={"body": comment},
        timeout=30
    )


def main():
    print("=" * 60)
    print("🤖 BA AGENT - Business Analysis")
    print("=" * 60)
    
    # Get configuration
    issue_number = os.environ.get('ISSUE_NUMBER')
    jira_feature_key = os.environ.get('JIRA_FEATURE_KEY')  # Passed from previous step
    
    if not issue_number:
        print("❌ ISSUE_NUMBER not set")
        sys.exit(1)
    
    if not jira_feature_key:
        print("❌ JIRA_FEATURE_KEY not set")
        sys.exit(1)
    
    try:
        # Initialize helpers
        jira = JiraHelper()
        confluence = ConfluenceHelper()
        slack = SlackHelper()
        claude = ClaudeHelper()
        
        # Step 1: Get GitHub issue
        print(f"\n📖 Fetching GitHub issue #{issue_number}...")
        issue = get_github_issue(issue_number)
        title = issue['title']
        description = issue.get('body', '')
        
        print(f"✅ Issue: {title}")
        
        # Step 2: Generate BA analysis with Claude
        print("\n🧠 Generating BA analysis with Claude...")
        prompt = PromptTemplates.ba_analysis(title, description)
        response = claude.generate_response(prompt, max_tokens=3000)
        ba_analysis = response['content']
        
        print(f"✅ Analysis complete ({response['tokens_used']} tokens, ${claude.get_cost()})")
        
        # Step 3: Post analysis to GitHub
        print("\n💬 Posting analysis to GitHub...")
        github_comment = f"""## 📋 BA Agent Analysis

{ba_analysis}

---
**Jira Feature:** [{jira_feature_key}]({jira.url}/browse/{jira_feature_key})
*Generated by BA Agent*"""
        
        post_github_comment(issue_number, github_comment)
        print("✅ Posted to GitHub")
        
        # Step 4: Create Confluence page
        print("\n📝 Creating Confluence documentation...")
        confluence_title = f"BA Analysis: {title}"
        confluence_content = f"""# Business Analysis

**Feature:** [{jira_feature_key}]({jira.url}/browse/{jira_feature_key})
**GitHub Issue:** [#{issue_number}](https://github.com/{os.environ['GITHUB_REPOSITORY']}/issues/{issue_number})
**Date:** {datetime.now().strftime('%Y-%m-%d')}

---

{ba_analysis}

---
*Generated by BA Agent*"""
        
        confluence_page = confluence.create_page(confluence_title, confluence_content)
        print(f"✅ Confluence page created: {confluence_page['url']}")
        
        # Step 5: Add comment to Jira feature with Confluence link
        print("\n📌 Updating Jira feature...")
        jira.add_comment(
            jira_feature_key,
            f"BA Analysis complete. View documentation: {confluence_page['url']}"
        )
        print("✅ Jira updated")
        
        # Step 6: Extract user stories and create in Jira
        print("\n👥 Extracting user stories...")
        extract_prompt = PromptTemplates.extract_user_stories(ba_analysis)
        stories_response = claude.generate_response(extract_prompt, max_tokens=2000)
        
        # Parse JSON response
        try:
            user_stories = json.loads(stories_response['content'])
            print(f"✅ Extracted {len(user_stories)} user stories")
        except json.JSONDecodeError:
            print("⚠️ Failed to parse user stories JSON, using default")
            user_stories = [
                {
                    "title": "Implement feature core functionality",
                    "description": f"As a developer, I want to implement {title}, so that users can benefit from it"
                }
            ]
        
        # Create user stories in Jira
        print("\n🎫 Creating user stories in Jira...")
        created_stories = []
        
        for story in user_stories[:5]:  # Limit to 5 stories
            story_title = story.get('title', 'User Story')
            story_desc = story.get('description', '')
            
            # Add acceptance criteria if present
            if 'acceptance_criteria' in story:
                criteria_text = "\n\nAcceptance Criteria:\n"
                criteria_text += "\n".join([f"- {c}" for c in story['acceptance_criteria']])
                story_desc += criteria_text
            
            jira_story = jira.create_user_story(story_title, story_desc, jira_feature_key)
            created_stories.append(jira_story['key'])
            print(f"  ✅ {jira_story['key']}: {story_title}")
        
        # Step 7: Save story keys for next agents
        print("\n💾 Saving user story keys...")
        with open('user_stories.json', 'w') as f:
            json.dump({
                'feature_key': jira_feature_key,
                'story_keys': created_stories,
                'confluence_url': confluence_page['url']
            }, f, indent=2)
        
        # Step 8: Send Slack notification
        print("\n📱 Sending Slack notification...")
        slack.notify_ba_complete(
            issue_number=int(issue_number),
            jira_key=jira_feature_key,
            confluence_url=confluence_page['url'],
            user_stories=[s.get('title', 'Story') for s in user_stories]
        )
        
        # Summary
        print("\n" + "=" * 60)
        print("✅ BA AGENT COMPLETED SUCCESSFULLY")
        print("=" * 60)
        print(f"📋 Feature: {jira_feature_key}")
        print(f"📝 Confluence: {confluence_page['url']}")
        print(f"🎫 User Stories: {len(created_stories)}")
        print(f"💰 Cost: ${claude.get_cost()}")
        print("=" * 60)
        
    except Exception as e:
        print(f"\n❌ BA Agent failed: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)


if __name__ == "__main__":
    main()
