#!/usr/bin/env python3
"""
BA Agent - Business Analyst
Analyzes requirements and creates Confluence documentation
"""

import os
import sys
import json
import requests
from datetime import datetime

# Add parent directory to path for imports
sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))

from utils import JiraHelper, ConfluenceHelper, SlackHelper, ClaudeHelper, PromptTemplates


def get_github_issue(issue_number: str):
    """Fetch GitHub issue details"""
    
    repo = os.environ['GITHUB_REPOSITORY']
    token = os.environ['GITHUB_TOKEN']
    
    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json"
    }
    
    response = requests.get(
        f"https://api.github.com/repos/{repo}/issues/{issue_number}",
        headers=headers,
        timeout=30
    )
    
    if response.status_code == 200:
        return response.json()
    else:
        raise Exception(f"Failed to fetch GitHub issue: {response.status_code}")


def post_github_comment(issue_number: str, comment: str):
    """Post a comment to GitHub issue with proper error handling"""
    
    repo = os.environ['GITHUB_REPOSITORY']
    token = os.environ['GITHUB_TOKEN']
    
    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json"
    }
    
    print(f"\n💬 Posting comment to GitHub issue #{issue_number}...")
    print(f"   Repository: {repo}")
    print(f"   Comment length: {len(comment)} characters")
    
    try:
        response = requests.post(
            f"https://api.github.com/repos/{repo}/issues/{issue_number}/comments",
            headers=headers,
            json={"body": comment},
            timeout=30
        )
        
        if response.status_code == 201:
            print("✅ GitHub comment posted successfully")
            comment_data = response.json()
            print(f"   Comment URL: {comment_data.get('html_url', 'N/A')}")
            return True
        else:
            print(f"❌ Failed to post GitHub comment: {response.status_code}")
            print(f"   Response: {response.text}")
            return False
    
    except Exception as e:
        print(f"❌ Error posting GitHub comment: {e}")
        import traceback
        traceback.print_exc()
        return False


def main():
    print("=" * 60)
    print("🤖 BA AGENT - Business Analysis")
    print("=" * 60)
    
    # Get configuration
    issue_number = os.environ.get('ISSUE_NUMBER')
    jira_feature_key = os.environ.get('JIRA_FEATURE_KEY')  # Passed from previous step
    
    if not issue_number:
        print("❌ ISSUE_NUMBER not set")
        sys.exit(1)
    
    if not jira_feature_key:
        print("❌ JIRA_FEATURE_KEY not set")
        sys.exit(1)
    
    try:
        # Initialize helpers
        jira = JiraHelper()
        confluence = ConfluenceHelper()
        slack = SlackHelper()
        claude = ClaudeHelper()
        
        # Step 1: Get GitHub issue
        print(f"\n📖 Fetching GitHub issue #{issue_number}...")
        issue = get_github_issue(issue_number)
        title = issue['title']
        description = issue.get('body', '')
        
        print(f"✅ Issue: {title}")
        
        # Step 2: Generate BA analysis with Claude
        print("\n🧠 Generating BA analysis with Claude...")
        prompt = PromptTemplates.ba_analysis(title, description)
        response = claude.generate_response(prompt, max_tokens=3000)
        ba_analysis = response['content']
        
        print(f"✅ Analysis complete ({response['tokens_used']} tokens, ${claude.get_cost()})")
        
        # Step 3: Create Confluence page
        print("\n📝 Creating Confluence documentation...")
        confluence_title = f"BA Analysis: {title}"
        current_datetime = datetime.now().strftime('%Y-%m-%d %H:%M UTC')
        
        confluence_content = f"""# Business Analysis

**Feature:** [{jira_feature_key}]({jira.url}/browse/{jira_feature_key})
**GitHub Issue:** [#{issue_number}](https://github.com/{os.environ['GITHUB_REPOSITORY']}/issues/{issue_number})
**Date:** {current_datetime}

---

{ba_analysis}

---
*Generated by BA Agent*"""
        
        confluence_page = confluence.create_page(confluence_title, confluence_content)
        print(f"✅ Confluence page created: {confluence_page['url']}")
        
        # Step 4: Update Jira issue description with BA analysis
        print("\n📋 Updating Jira issue description...")
        
        jira_description = f"""Business Analysis - {current_datetime}

GitHub Issue: https://github.com/{os.environ['GITHUB_REPOSITORY']}/issues/{issue_number}
Confluence: {confluence_page['url']}

---

{ba_analysis}

---
Generated by BA Agent"""
        
        jira_updated = jira.update_issue_description(jira_feature_key, jira_description)
        
        if jira_updated:
            print("✅ Jira description updated with BA analysis")
        else:
            print("⚠️ Jira description update failed, but continuing...")
        
        # Step 5: Post SAME analysis to GitHub (matching Confluence)
        github_comment = f"""## 📋 Business Analysis

**Feature:** [{jira_feature_key}]({jira.url}/browse/{jira_feature_key})
**GitHub Issue:** [#{issue_number}](https://github.com/{os.environ['GITHUB_REPOSITORY']}/issues/{issue_number})
**Date:** {current_datetime}
**Confluence:** [View Full Documentation]({confluence_page['url']})

---

{ba_analysis}

---

### 📊 Next Steps
- ✅ Requirements analysis complete
- ✅ Documentation available in Confluence
- ✅ Jira issue updated with full requirements
- ✅ Developers can review and start planning

*Generated by BA Agent*"""
        
        # Post to GitHub with better error handling
        github_success = post_github_comment(issue_number, github_comment)
        
        if not github_success:
            print("⚠️ GitHub comment failed but continuing with workflow...")
        
        # Step 6: Add comment to Jira feature with Confluence link
        print("\n📌 Adding comment to Jira feature...")
        jira.add_comment(
            jira_feature_key,
            f"BA Analysis complete. View full documentation: {confluence_page['url']}"
        )
        print("✅ Jira comment added")
        
        # Step 7: Send Slack notification
        print("\n📱 Sending Slack notification...")
        
        if slack.enabled:
            # Custom message for BA completion
            slack_success = slack.send_message(
                f"✅ Requirements Ready - {jira_feature_key}",
                blocks=[
                    {
                        "type": "header",
                        "text": {
                            "type": "plain_text",
                            "text": "✅ Requirements Analysis Complete"
                        }
                    },
                    {
                        "type": "section",
                        "fields": [
                            {
                                "type": "mrkdwn",
                                "text": f"*Feature:*\n{jira_feature_key}"
                            },
                            {
                                "type": "mrkdwn",
                                "text": f"*Title:*\n{title}"
                            }
                        ]
                    },
                    {
                        "type": "section",
                        "text": {
                            "type": "mrkdwn",
                            "text": "🚀 *Requirements are ready. Developers can proceed with development.*"
                        }
                    },
                    {
                        "type": "actions",
                        "elements": [
                            {
                                "type": "button",
                                "text": {
                                    "type": "plain_text",
                                    "text": "View Confluence Doc"
                                },
                                "url": confluence_page['url'],
                                "style": "primary"
                            },
                            {
                                "type": "button",
                                "text": {
                                    "type": "plain_text",
                                    "text": "View Jira"
                                },
                                "url": f"{jira.url}/browse/{jira_feature_key}"
                            },
                            {
                                "type": "button",
                                "text": {
                                    "type": "plain_text",
                                    "text": "View GitHub Issue"
                                },
                                "url": f"https://github.com/{os.environ['GITHUB_REPOSITORY']}/issues/{issue_number}"
                            }
                        ]
                    },
                    {
                        "type": "context",
                        "elements": [
                            {
                                "type": "mrkdwn",
                                "text": f"📋 GitHub Issue #{issue_number} | 📝 Jira Description Updated | ⏰ {current_datetime}"
                            }
                        ]
                    }
                ]
            )
            
            if slack_success:
                print("✅ Slack notification sent")
            else:
                print("⚠️ Slack notification failed")
        else:
            print("⚠️ Slack webhook not configured - skipping notification")
        
        # Summary
        print("\n" + "=" * 60)
        print("✅ BA AGENT COMPLETED SUCCESSFULLY")
        print("=" * 60)
        print(f"📋 Feature: {jira_feature_key}")
        print(f"📝 Confluence: {confluence_page['url']}")
        print(f"📋 Jira description: {'✅ Updated' if jira_updated else '⚠️ Failed'}")
        print(f"💬 GitHub comment: {'✅ Posted' if github_success else '❌ Failed'}")
        print(f"💰 Cost: ${claude.get_cost()}")
        print("=" * 60)
        
    except Exception as e:
        print(f"\n❌ BA Agent failed: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)


if __name__ == "__main__":
    main()
