#!/usr/bin/env python3
"""
PM Agent - Project Manager
Creates sprint planning documentation
"""

import os
import sys
import json
from datetime import datetime

sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))

from utils import ConfluenceHelper, SlackHelper, ClaudeHelper, PromptTemplates


def main():
    print("=" * 60)
    print("🤖 PM AGENT - Sprint Planning")
    print("=" * 60)
    
    try:
        # Load user stories from BA agent
        print("\n📖 Loading user stories...")
        with open('user_stories.json', 'r') as f:
            data = json.load(f)
        
        feature_key = data['feature_key']
        story_keys = data['story_keys']
        ba_confluence_url = data.get('confluence_url')
        
        print(f"✅ Feature: {feature_key}")
        print(f"✅ User Stories: {len(story_keys)}")
        
        # Initialize helpers
        confluence = ConfluenceHelper()
        slack = SlackHelper()
        claude = ClaudeHelper()
        
        # Generate sprint planning with Claude
        print("\n🧠 Generating sprint planning document...")
        feature_title = os.environ.get('FEATURE_TITLE', feature_key)
        
        prompt = PromptTemplates.sprint_planning(
            feature_title=feature_title,
            user_stories=story_keys,
            team_size=5
        )
        
        response = claude.generate_response(prompt, max_tokens=3000)
        sprint_plan = response['content']
        
        print(f"✅ Sprint plan generated ({response['tokens_used']} tokens)")
        
        # Create Confluence page
        print("\n📝 Creating Sprint Planning page in Confluence...")
        
        sprint_title = f"Sprint Planning: {feature_title}"
        sprint_content = f"""# Sprint Planning

**Feature:** {feature_key}
**Created:** {datetime.now().strftime('%Y-%m-%d %H:%M UTC')}
**BA Documentation:** [View Analysis]({ba_confluence_url})

---

## User Stories in Sprint
{chr(10).join([f'- {key}' for key in story_keys])}

---

{sprint_plan}

---

## Daily Standup Updates
Updates will be posted below by PM Agent after code merges.

---
*Generated by PM Agent*"""
        
        sprint_page = confluence.create_page(sprint_title, sprint_content)
        print(f"✅ Sprint Planning page: {sprint_page['url']}")
        
        # Save sprint page ID for standup updates
        with open('sprint_planning.json', 'w') as f:
            json.dump({
                'page_id': sprint_page['id'],
                'page_url': sprint_page['url'],
                'feature_key': feature_key,
                'story_keys': story_keys
            }, f, indent=2)
        
        # Send Slack notification
        print("\n📱 Sending Slack notification...")
        slack.send_message(
            f"📅 Sprint Planning Complete for {feature_key}",
            blocks=[
                {
                    "type": "header",
                    "text": {
                        "type": "plain_text",
                        "text": "📅 Sprint Planning Ready"
                    }
                },
                {
                    "type": "section",
                    "fields": [
                        {
                            "type": "mrkdwn",
                            "text": f"*Feature:*\n{feature_key}"
                        },
                        {
                            "type": "mrkdwn",
                            "text": f"*User Stories:*\n{len(story_keys)}"
                        }
                    ]
                },
                {
                    "type": "actions",
                    "elements": [
                        {
                            "type": "button",
                            "text": {
                                "type": "plain_text",
                                "text": "View Sprint Plan"
                            },
                            "url": sprint_page['url'],
                            "style": "primary"
                        }
                    ]
                }
            ]
        )
        
        # Summary
        print("\n" + "=" * 60)
        print("✅ PM AGENT (SPRINT PLANNING) COMPLETED")
        print("=" * 60)
        print(f"📅 Sprint Plan: {sprint_page['url']}")
        print(f"🎫 Stories: {len(story_keys)}")
        print(f"💰 Cost: ${claude.get_cost()}")
        print("=" * 60)
        
    except Exception as e:
        print(f"\n❌ PM Agent failed: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)


if __name__ == "__main__":
    main()
