#!/usr/bin/env python3
"""
PR Review Agent
Performs automated code review on pull requests
"""

import os
import sys
import requests

sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))

from utils import SlackHelper, ClaudeHelper, PromptTemplates


def get_pr_details(pr_number):
    """Get PR details"""
    
    repo = os.environ['GITHUB_REPOSITORY']
    token = os.environ['GITHUB_TOKEN']
    
    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json"
    }
    
    response = requests.get(
        f"https://api.github.com/repos/{repo}/pulls/{pr_number}",
        headers=headers,
        timeout=30
    )
    
    return response.json()


def get_pr_diff(pr_number):
    """Get unified diff for PR"""
    
    repo = os.environ['GITHUB_REPOSITORY']
    token = os.environ['GITHUB_TOKEN']
    
    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github.v3.diff"
    }
    
    response = requests.get(
        f"https://api.github.com/repos/{repo}/pulls/{pr_number}",
        headers=headers,
        timeout=30
    )
    
    return response.text[:4000]  # Limit diff size


def post_review_comment(pr_number, comment):
    """Post review comment"""
    
    repo = os.environ['GITHUB_REPOSITORY']
    token = os.environ['GITHUB_TOKEN']
    
    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json"
    }
    
    requests.post(
        f"https://api.github.com/repos/{repo}/issues/{pr_number}/comments",
        headers=headers,
        json={"body": comment},
        timeout=30
    )


def main():
    print("=" * 60)
    print("🤖 PR REVIEW AGENT")
    print("=" * 60)
    
    pr_number = os.environ.get('PR_NUMBER')
    
    if not pr_number:
        print("❌ PR_NUMBER not set")
        sys.exit(1)
    
    try:
        # Initialize helpers
        slack = SlackHelper()
        claude = ClaudeHelper()
        
        # Get PR details
        print(f"\n📖 Fetching PR #{pr_number}...")
        pr = get_pr_details(pr_number)
        pr_title = pr['title']
        pr_description = pr.get('body', '')
        pr_url = pr['html_url']
        
        print(f"✅ PR: {pr_title}")
        
        # Get diff
        print("\n📂 Getting code diff...")
        diff = get_pr_diff(pr_number)
        print(f"✅ Got {len(diff)} chars of diff")
        
        # Generate code review with Claude
        print("\n🧠 Performing code review...")
        prompt = PromptTemplates.pr_review(pr_title, pr_description, diff)
        response = claude.generate_response(prompt, max_tokens=3000)
        review = response['content']
        
        print(f"✅ Review complete ({response['tokens_used']} tokens)")
        
        # Post to GitHub
        print("\n💬 Posting review to GitHub...")
        github_comment = f"""## 👨‍💻 PR Review Agent

{review}

---
**Note:** This is an automated review. Human approval still required for merge.

*Generated by PR Review Agent*"""
        
        post_review_comment(pr_number, github_comment)
        print("✅ Posted to GitHub")
        
        # Analyze review sentiment
        issues_found = review.lower().count('issue') + review.lower().count('bug') + review.lower().count('error')
        suggestions_made = review.lower().count('suggest') + review.lower().count('consider') + review.lower().count('recommend')
        
        # Send Slack notification
        print("\n📱 Sending Slack notification...")
        
        if issues_found == 0:
            status_emoji = "✅"
            status_text = "Code looks good!"
        elif issues_found <= 3:
            status_emoji = "⚠️"
            status_text = "Minor issues found"
        else:
            status_emoji = "🔴"
            status_text = "Review needed"
        
        slack.send_message(
            f"{status_emoji} PR Review: {pr_title}",
            blocks=[
                {
                    "type": "header",
                    "text": {
                        "type": "plain_text",
                        "text": f"👨‍💻 PR Review Complete: #{pr_number}"
                    }
                },
                {
                    "type": "section",
                    "text": {
                        "type": "mrkdwn",
                        "text": f"*PR:* {pr_title}\n*Status:* {status_emoji} {status_text}"
                    }
                },
                {
                    "type": "section",
                    "fields": [
                        {
                            "type": "mrkdwn",
                            "text": f"*Issues:*\n~{issues_found}"
                        },
                        {
                            "type": "mrkdwn",
                            "text": f"*Suggestions:*\n💡 {suggestions_made}"
                        }
                    ]
                },
                {
                    "type": "actions",
                    "elements": [
                        {
                            "type": "button",
                            "text": {
                                "type": "plain_text",
                                "text": "View PR"
                            },
                            "url": pr_url
                        }
                    ]
                }
            ]
        )
        
        # Summary
        print("\n" + "=" * 60)
        print("✅ PR REVIEW AGENT COMPLETED")
        print("=" * 60)
        print(f"📝 PR: #{pr_number}")
        print(f"🔍 Issues: ~{issues_found}")
        print(f"💡 Suggestions: {suggestions_made}")
        print(f"💰 Cost: ${claude.get_cost()}")
        print("=" * 60)
        
    except Exception as e:
        print(f"\n❌ PR Review Agent failed: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)


if __name__ == "__main__":
    main()
